/** Варвары (§10.1): кожа, мех, ржавое железо — гоблины, орки, огры, гиганты и звери */
import { type UnitSource, humanoid } from '../figures/humanoid.js'
import { quadruped } from '../figures/quadruped.js'
import { bird } from '../figures/dragon.js'
import * as K from './tones.js'

const RUST = K.t('#d8a882', '#8a5a3a', '#2a1408', 'metal')
const WAR_PAINT = '#b02a1a'

export const BARBARIAN_RIGS: Record<string, () => UnitSource> = {
  barbarian_goblin: () => humanoid({
    id: 'bgob',
    height: 0.78,
    headScale: 1.2,
    skin: K.SKIN_GOBLIN,
    head: { kind: 'goblin', ears: 'big' },
    torso: { kind: 'leather', tone: K.LEATHER, belt: K.LEATHER },
    legs: { kind: 'pants', tone: K.HOMESPUN, boots: K.LEATHER },
    pose: 'melee',
    weapon: { kind: 'club' },
    off: { kind: 'buckler', tone: K.WOOD },
    motion: 'walk',
    attack: 'swing',
  }),
  barbarian_goblin_spearthrower: () => humanoid({
    id: 'bgobsp',
    height: 0.78,
    headScale: 1.2,
    skin: K.SKIN_GOBLIN,
    head: { kind: 'goblin', ears: 'big', hair: { tone: K.HAIR_BLACK, style: 'mohawk' } },
    torso: { kind: 'fur', tone: K.SKIN_GOBLIN, belt: K.LEATHER },
    legs: { kind: 'pants', tone: K.LEATHER },
    pose: 'throw',
    weapon: { kind: 'javelin', tone: RUST },
    motion: 'walk',
    attack: 'bow',
  }),
  barbarian_wolf_rider: () => quadruped({
    id: 'bwolfr',
    species: 'wolf',
    tone: K.t('#a89a8a', '#5a4e44', '#16120e', 'cloth'),
    mane: K.FUR_DARK,
    eyes: '#ffd040',
    scale: 1.02,
    rider: {
      id: 'bwolfr',
      height: 0.72,
      headScale: 1.2,
      skin: K.SKIN_GOBLIN,
      head: { kind: 'goblin', ears: 'big', helmet: { kind: 'cap', tone: K.LEATHER } },
      torso: { kind: 'leather', tone: K.LEATHER },
      legs: { kind: 'pants', tone: K.LEATHER },
      pose: 'melee',
      weapon: { kind: 'axe', tone: RUST },
      motion: 'gallop',
      attack: 'swing',
    },
    motion: 'gallop',
    attack: 'swing',
  }),
  barbarian_orc_warrior: () => humanoid({
    id: 'borc',
    bulk: 1.18,
    skin: K.SKIN_ORC,
    head: { kind: 'orc', tusks: true, hair: { tone: K.HAIR_BLACK, style: 'mohawk' } },
    torso: { kind: 'fur', tone: K.SKIN_ORC, belt: K.LEATHER, skirt: 'short' },
    legs: { kind: 'pants', tone: K.LEATHER, boots: K.FUR_DARK },
    arms: { sleeve: K.SKIN_ORC },
    pose: 'melee',
    weapon: { kind: 'axe', tone: RUST },
    off: { kind: 'shield_round', tone: K.WOOD, emblem: WAR_PAINT },
    motion: 'walk',
    attack: 'swing',
  }),
  barbarian_orc_axe_thrower: () => humanoid({
    id: 'borcax',
    bulk: 1.12,
    skin: K.SKIN_ORC,
    head: { kind: 'orc', tusks: true, hair: { tone: K.HAIR_BLACK, style: 'long' } },
    torso: { kind: 'leather', tone: K.LEATHER, belt: K.LEATHER },
    legs: { kind: 'pants', tone: K.FUR, boots: K.LEATHER },
    arms: { sleeve: K.SKIN_ORC },
    pose: 'throw',
    weapon: { kind: 'axe', tone: RUST, scale: 0.8 },
    motion: 'walk',
    attack: 'bow',
  }),
  barbarian_berserker: () => humanoid({
    id: 'bbers',
    bulk: 1.2,
    skin: K.SKIN_TAN,
    head: { kind: 'human', hair: { tone: K.HAIR_RED, style: 'wild' }, beard: { tone: K.HAIR_RED, style: 'braided' }, eyes: '#ff6a3a' },
    torso: { kind: 'bare', tone: K.SKIN_TAN, belt: K.LEATHER },
    legs: { kind: 'pants', tone: K.FUR, boots: K.FUR_DARK },
    pose: 'twohand',
    weapon: { kind: 'greataxe', tone: RUST },
    extra: { torso: `<path d="M48,40 l6,6 M50,36 l6,6" stroke="${WAR_PAINT}" stroke-width="1.2" opacity="0.8"/>` },
    motion: 'walk',
    attack: 'swing',
  }),
  barbarian_ogre: () => humanoid({
    id: 'bogre',
    height: 1.08,
    bulk: 1.5,
    headScale: 0.92,
    skin: K.SKIN_OGRE,
    head: { kind: 'brute', tusks: true, ears: 'round' },
    torso: { kind: 'bare', tone: K.SKIN_OGRE, belt: K.LEATHER, skirt: 'short' },
    legs: { kind: 'bare' },
    pose: 'twohand',
    weapon: { kind: 'club', scale: 1.3 },
    motion: 'walk',
    attack: 'swing',
  }),
  barbarian_ogre_shaman: () => humanoid({
    id: 'boshm',
    height: 1.06,
    bulk: 1.45,
    headScale: 0.92,
    skin: K.SKIN_OGRE,
    head: { kind: 'brute', tusks: true, horns: { tone: K.HORN, kind: 'small' }, eyes: '#8ad8ff' },
    torso: { kind: 'fur', tone: K.SKIN_OGRE, belt: K.LEATHER, skirt: 'long' },
    legs: { kind: 'bare' },
    pose: 'cast',
    weapon: { kind: 'staff', glow: '#8ad8ff' },
    castGlow: '#8ad8ff',
    motion: 'walk',
    attack: 'cast',
  }),
  barbarian_thunderbird: () => bird({
    id: 'bthund',
    tone: K.t('#a8b8d8', '#3a4a6a', '#0c1220'),
    wing: K.t('#c8d8f0', '#4a5a7a', '#0c1220'),
    beak: K.t('#fff0c0', '#d8b048', '#5a3a08'),
    crest: K.t('#ffffff', '#ffe070', '#8a6a10'),
    lightning: '#c8ecff',
    eyes: '#ffffff',
    motion: 'fly',
    attack: 'bite',
  }),
  barbarian_war_troll: () => humanoid({
    id: 'btroll',
    height: 1.1,
    bulk: 1.35,
    headScale: 0.88,
    skin: K.SKIN_TROLL,
    head: { kind: 'brute', tusks: true, ears: 'pointed', hair: { tone: K.HAIR_BLACK, style: 'wild' } },
    torso: { kind: 'bare', tone: K.SKIN_TROLL, belt: K.LEATHER, skirt: 'short' },
    legs: { kind: 'bare' },
    pose: 'melee',
    weapon: { kind: 'club', scale: 1.15 },
    motion: 'walk',
    attack: 'swing',
  }),
  barbarian_cyclops: () => humanoid({
    id: 'bcycl',
    height: 1.12,
    bulk: 1.45,
    skin: K.SKIN_OGRE,
    head: { kind: 'cyclops', ears: 'round' },
    torso: { kind: 'fur', tone: K.SKIN_OGRE, belt: K.LEATHER, skirt: 'short' },
    legs: { kind: 'bare' },
    pose: 'throw',
    weapon: { kind: 'rock', scale: 2 },
    motion: 'walk',
    attack: 'bow',
  }),
  barbarian_hill_giant: () => humanoid({
    id: 'bgiant',
    height: 1.12,
    bulk: 1.55,
    skin: K.SKIN_TAN,
    head: { kind: 'brute', beard: { tone: K.HAIR_BROWN, style: 'long' }, hair: { tone: K.HAIR_BROWN, style: 'wild' } },
    torso: { kind: 'fur', tone: K.SKIN_TAN, belt: K.LEATHER, skirt: 'short' },
    legs: { kind: 'bare' },
    pose: 'twohand',
    weapon: { kind: 'club', scale: 1.5 },
    motion: 'walk',
    attack: 'swing',
  }),
  barbarian_mammoth: () => quadruped({
    id: 'bmamm',
    species: 'mammoth',
    tone: K.t('#a8805a', '#5a3a22', '#1a0e06', 'cloth'),
    tusks: true,
    tail: 'normal',
    motion: 'gallop',
    attack: 'thrust',
  }),
  barbarian_war_rhino: () => quadruped({
    id: 'brhino',
    species: 'rhino',
    tone: K.t('#b8b0a8', '#6a625a', '#1e1a16', 'leather'),
    barding: { tone: RUST, trim: WAR_PAINT },
    tail: 'stub',
    motion: 'gallop',
    attack: 'thrust',
  }),
}
