/** Демоны (§10.1): багровая кожа, чёрное железо и пламя преисподней */
import { type UnitSource, humanoid } from '../figures/humanoid.js'
import { quadruped } from '../figures/quadruped.js'
import * as K from './tones.js'

const FIRE = '#ff8a2a'
const HELLFIRE = '#ffb02e'
const BLACK_IRON = K.t('#8a7a7a', '#3a2a2a', '#0a0404', 'metal')
const HELL_HORSE = K.t('#5a4a4a', '#1e1414', '#000000', 'skin')
const MAGMA_CRACKS = `<path d="M42,44 l5,4 l-2,6 l5,4 M54,36 l-3,6 l4,4" fill="none" stroke="#ffb02e" stroke-width="1" opacity="0.9"/>`

export const DEMON_RIGS: Record<string, () => UnitSource> = {
  demon_imp: () => humanoid({
    id: 'dimp',
    height: 0.72,
    headScale: 1.25,
    skin: K.SKIN_DEMON,
    head: { kind: 'demon', horns: { tone: K.HORN_DARK, kind: 'small' }, eyes: HELLFIRE, ears: 'big' },
    torso: { kind: 'bare', tone: K.SKIN_DEMON },
    legs: { kind: 'hooves', tone: K.SKIN_DEMON },
    pose: 'claws',
    wings: { kind: 'bat', tone: K.SKIN_DEMON_DARK, span: 0.6 },
    tail: { kind: 'demon', tone: K.SKIN_DEMON },
    motion: 'walk',
    attack: 'claw',
  }),
  demon_familiar: () => humanoid({
    id: 'dfam',
    height: 0.7,
    headScale: 1.25,
    skin: K.t('#d8a8e8', '#7a3a9a', '#200a2a', 'skin'),
    head: { kind: 'demon', horns: { tone: K.HORN_DARK, kind: 'ram' }, eyes: '#e0a8ff', ears: 'pointed' },
    torso: { kind: 'bare', tone: K.t('#d8a8e8', '#7a3a9a', '#200a2a', 'skin') },
    legs: { kind: 'smoke', tone: K.t('#e8c8ff', '#8a5ab0', '#2a0a3a') },
    pose: 'cast',
    castGlow: '#e0a8ff',
    tail: { kind: 'demon', tone: K.t('#d8a8e8', '#7a3a9a', '#200a2a', 'skin') },
    aura: { color: '#c88aff', strength: 0.2 },
    hover: 8,
    motion: 'float',
    attack: 'cast',
  }),
  demon_hellhound: () => quadruped({
    id: 'dhound',
    species: 'wolf',
    tone: K.t('#6a4a44', '#2a1614', '#060202', 'skin'),
    mane: K.t('#ffd070', '#ff6a1a', '#6a1004'),
    eyes: HELLFIRE,
    fire: FIRE,
    tail: 'flame',
    motion: 'gallop',
    attack: 'bite',
  }),
  demon_horned_demon: () => humanoid({
    id: 'dhorn',
    bulk: 1.3,
    skin: K.SKIN_DEMON,
    head: { kind: 'demon', horns: { tone: K.HORN_DARK, kind: 'ram' }, eyes: HELLFIRE, tusks: true },
    torso: { kind: 'bare', tone: K.SKIN_DEMON, belt: BLACK_IRON, skirt: 'short' },
    legs: { kind: 'hooves', tone: K.SKIN_DEMON_DARK },
    pose: 'twohand',
    weapon: { kind: 'trident', tone: BLACK_IRON },
    tail: { kind: 'demon', tone: K.SKIN_DEMON },
    motion: 'walk',
    attack: 'thrust',
  }),
  demon_succubus: () => humanoid({
    id: 'dsucc',
    skin: K.t('#ffc8c8', '#d07a80', '#4a1a20', 'skin'),
    head: { kind: 'female', hair: { tone: K.HAIR_BLACK, style: 'long' }, horns: { tone: K.HORN_DARK, kind: 'long' }, eyes: '#ff70a0' },
    torso: { kind: 'leather', tone: K.LEATHER_DARK, belt: BLACK_IRON, skirt: 'short' },
    legs: { kind: 'bare' },
    pose: 'cast',
    castGlow: '#ff6a9a',
    wings: { kind: 'bat', tone: K.SKIN_DEMON_DARK, span: 0.95 },
    tail: { kind: 'demon', tone: K.t('#ffc8c8', '#d07a80', '#4a1a20', 'skin') },
    motion: 'walk',
    attack: 'cast',
  }),
  demon_flame_lasher: () => humanoid({
    id: 'dlash',
    bulk: 1.1,
    skin: K.SKIN_DEMON,
    head: { kind: 'demon', horns: { tone: K.HORN_DARK, kind: 'bull' }, eyes: HELLFIRE, hair: { tone: K.HAIR_BLACK, style: 'flame' } },
    torso: { kind: 'leather', tone: K.LEATHER_DARK, belt: BLACK_IRON },
    legs: { kind: 'hooves', tone: K.SKIN_DEMON_DARK },
    pose: 'melee',
    weapon: { kind: 'whip', glow: FIRE },
    tail: { kind: 'demon', tone: K.SKIN_DEMON },
    motion: 'walk',
    attack: 'swing',
  }),
  demon_nightmare: () => quadruped({
    id: 'dnight',
    species: 'horse',
    tone: HELL_HORSE,
    mane: K.t('#ffe070', '#ff6a1a', '#6a1004'),
    eyes: HELLFIRE,
    fire: FIRE,
    tail: 'flame',
    motion: 'gallop',
    attack: 'thrust',
  }),
  demon_cerberus: () => quadruped({
    id: 'dcerb',
    species: 'wolf',
    tone: K.t('#7a5a50', '#3a201c', '#0a0404', 'skin'),
    mane: K.t('#ffd070', '#ff6a1a', '#6a1004'),
    eyes: HELLFIRE,
    heads: 3,
    fire: FIRE,
    tail: 'normal',
    scale: 1.04,
    motion: 'gallop',
    attack: 'bite',
  }),
  demon_infernal_fiend: () => humanoid({
    id: 'dfiend',
    height: 1.08,
    bulk: 1.45,
    skin: K.SKIN_DEMON_DARK,
    head: { kind: 'demon', horns: { tone: K.HORN_DARK, kind: 'long' }, eyes: HELLFIRE, tusks: true },
    torso: { kind: 'bare', tone: K.SKIN_DEMON_DARK, belt: BLACK_IRON, skirt: 'short' },
    legs: { kind: 'hooves', tone: K.SKIN_DEMON_DARK },
    pose: 'claws',
    tail: { kind: 'demon', tone: K.SKIN_DEMON_DARK },
    aura: { color: FIRE, strength: 0.3 },
    extra: { torso: MAGMA_CRACKS },
    motion: 'walk',
    attack: 'claw',
  }),
  demon_brimstone_thrower: () => humanoid({
    id: 'dbrim',
    bulk: 1.2,
    skin: K.SKIN_DEMON,
    head: { kind: 'demon', horns: { tone: K.HORN_DARK, kind: 'ram' }, eyes: HELLFIRE },
    torso: { kind: 'leather', tone: BLACK_IRON, belt: K.LEATHER },
    legs: { kind: 'hooves', tone: K.SKIN_DEMON_DARK },
    pose: 'throw',
    weapon: { kind: 'rock', scale: 1.4, glow: FIRE },
    tail: { kind: 'demon', tone: K.SKIN_DEMON },
    motion: 'walk',
    attack: 'bow',
  }),
  demon_efreet: () => humanoid({
    id: 'defreet',
    bulk: 1.2,
    skin: K.SKIN_FIRE,
    head: { kind: 'demon', hair: { tone: K.HAIR_RED, style: 'flame' }, eyes: '#ffffff', beard: { tone: K.t('#fff0a0', '#ff8a2a', '#7a1a04'), style: 'short' } },
    torso: { kind: 'bare', tone: K.SKIN_FIRE, belt: K.GOLD },
    legs: { kind: 'smoke', tone: K.t('#fff0a0', '#ff7a1a', '#5a1004') },
    arms: { sleeve: K.SKIN_FIRE },
    pose: 'melee',
    weapon: { kind: 'scimitar', tone: K.GOLD, glow: FIRE },
    aura: { color: FIRE, strength: 0.35 },
    hover: 4,
    motion: 'float',
    attack: 'swing',
  }),
  demon_lava_brute: () => humanoid({
    id: 'dlava',
    height: 1.1,
    bulk: 1.6,
    headScale: 0.85,
    skin: K.SKIN_MAGMA,
    head: { kind: 'brute', eyes: HELLFIRE, horns: { tone: K.HORN_DARK, kind: 'small' } },
    torso: { kind: 'stone', tone: K.SKIN_MAGMA },
    legs: { kind: 'bare' },
    pose: 'melee',
    weapon: { kind: 'none' },
    aura: { color: FIRE, strength: 0.3 },
    extra: { torso: MAGMA_CRACKS + `<path d="M38,52 l6,2 l2,6 M58,48 l-4,6" fill="none" stroke="#ffd070" stroke-width="1.2"/>` },
    motion: 'walk',
    attack: 'swing',
  }),
  demon_archfiend: () => humanoid({
    id: 'darch',
    height: 1.12,
    bulk: 1.35,
    skin: K.SKIN_DEMON_DARK,
    head: { kind: 'demon', horns: { tone: K.HORN_DARK, kind: 'long' }, eyes: HELLFIRE, hair: { tone: K.HAIR_BLACK, style: 'long' } },
    torso: { kind: 'plate', tone: BLACK_IRON, pauldrons: BLACK_IRON, belt: K.GOLD, skirt: 'long' },
    legs: { kind: 'hooves', tone: K.SKIN_DEMON_DARK },
    arms: { sleeve: K.SKIN_DEMON_DARK, gauntlet: BLACK_IRON },
    pose: 'melee',
    weapon: { kind: 'greatsword', tone: BLACK_IRON, glow: FIRE },
    wings: { kind: 'bat', tone: K.SKIN_DEMON_DARK, span: 1.25 },
    tail: { kind: 'demon', tone: K.SKIN_DEMON_DARK },
    aura: { color: FIRE, strength: 0.22 },
    motion: 'walk',
    attack: 'swing',
  }),
  demon_doom_lord: () => humanoid({
    id: 'ddoom',
    height: 1.12,
    bulk: 1.5,
    skin: K.SKIN_DEMON,
    head: { kind: 'demon', horns: { tone: K.HORN_DARK, kind: 'ram' }, eyes: HELLFIRE, helmet: { kind: 'great', tone: BLACK_IRON } },
    torso: { kind: 'plate', tone: BLACK_IRON, pauldrons: BLACK_IRON, belt: K.GOLD, skirt: 'long', trim: K.GOLD },
    legs: { kind: 'plate', tone: BLACK_IRON, boots: BLACK_IRON },
    arms: { sleeve: BLACK_IRON, gauntlet: BLACK_IRON },
    pose: 'twohand',
    weapon: { kind: 'greataxe', tone: BLACK_IRON, glow: FIRE, scale: 1.15 },
    cape: K.cloth('#d8505a', '#7a1a20', '#200406'),
    aura: { color: FIRE, strength: 0.3 },
    motion: 'walk',
    attack: 'swing',
  }),
}
