/** Подземелье (§10.1): фиолетовый сумрак, вороная сталь — тёмные эльфы и чудовища глубин */
import { type UnitSource, humanoid } from '../figures/humanoid.js'
import { quadruped, spider } from '../figures/quadruped.js'
import { dragon } from '../figures/dragon.js'
import * as K from './tones.js'

const PURPLE = K.cloth('#c8a0e8', '#6a2a8f', '#1c0a2a')
const NIGHT = K.cloth('#7a7a9a', '#2a3a5a', '#0a0e1a')
const SHADOW = '#c46bff'
const DARKSTEEL = K.t('#a8a0c0', '#4a4460', '#100c1a', 'metal')

export const DUNGEON_RIGS: Record<string, () => UnitSource> = {
  dungeon_troglodyte: () => humanoid({
    id: 'gtrog',
    height: 0.92,
    bulk: 1.1,
    skin: K.SKIN_LIZARD,
    head: { kind: 'lizard', ears: 'none' },
    torso: { kind: 'bare', tone: K.SKIN_LIZARD, belt: K.LEATHER, skirt: 'short' },
    legs: { kind: 'bare' },
    pose: 'spear',
    weapon: { kind: 'spear', tone: K.t('#d8d0c0', '#8a8070', '#2a2418', 'bone') },
    tail: { kind: 'lizard', tone: K.SKIN_LIZARD },
    motion: 'walk',
    attack: 'thrust',
  }),
  dungeon_cave_spider: () => spider({ id: 'gspid', tone: K.t('#7a6a8a', '#2a2232', '#060408', 'leather'), mark: '#c42a2a', eyes: '#ff5a5a', motion: 'gallop', attack: 'bite' }),
  dungeon_harpy: () => humanoid({
    id: 'gharpy',
    height: 0.92,
    skin: K.t('#f0d8c8', '#b08a7a', '#4a2a22', 'skin'),
    head: { kind: 'female', hair: { tone: K.t('#a8a0c0', '#5a4a6a', '#1a1222'), style: 'wild' }, eyes: '#ffe070' },
    torso: { kind: 'fur', tone: K.t('#f0d8c8', '#b08a7a', '#4a2a22', 'skin') },
    legs: { kind: 'hooves', tone: K.t('#c8b8a8', '#6a5a4a', '#1a120a', 'cloth') },
    pose: 'claws',
    wings: { kind: 'feather', tone: K.t('#c8b8d8', '#5a4a6a', '#140c1c', 'cloth'), span: 0.95 },
    hover: 8,
    motion: 'fly',
    attack: 'claw',
  }),
  dungeon_dark_scout: () => humanoid({
    id: 'gscout',
    skin: K.SKIN_DARKELF,
    head: { kind: 'elf', hair: { tone: K.HAIR_WHITE, style: 'long' }, helmet: { kind: 'hood', tone: NIGHT }, eyes: '#ff7a7a' },
    torso: { kind: 'leather', tone: K.LEATHER_DARK, belt: K.LEATHER_DARK },
    legs: { kind: 'pants', tone: K.LEATHER_DARK },
    pose: 'bow',
    off: { kind: 'bow', tone: K.t('#7a6a8a', '#2a2232', '#060408') },
    cape: NIGHT,
    motion: 'walk',
    attack: 'bow',
  }),
  dungeon_shadow_crossbowman: () => humanoid({
    id: 'gxbow',
    skin: K.SKIN_DARKELF,
    head: { kind: 'elf', hair: { tone: K.HAIR_WHITE, style: 'long' }, helmet: { kind: 'kettle', tone: DARKSTEEL } },
    torso: { kind: 'chain', tone: DARKSTEEL, tabard: { tone: PURPLE }, belt: K.LEATHER_DARK },
    legs: { kind: 'pants', tone: K.LEATHER_DARK },
    pose: 'crossbow',
    off: { kind: 'crossbow', tone: K.t('#7a6a8a', '#2a2232', '#060408', 'wood') },
    motion: 'walk',
    attack: 'bow',
  }),
  dungeon_assassin: () => humanoid({
    id: 'gassn',
    skin: K.SKIN_DARKELF,
    head: { kind: 'elf', helmet: { kind: 'hood', tone: K.cloth('#5a5a6a', '#1a1a24', '#000000') }, eyes: SHADOW },
    torso: { kind: 'leather', tone: K.cloth('#5a5a6a', '#1a1a24', '#000000'), belt: K.LEATHER_DARK },
    legs: { kind: 'pants', tone: K.cloth('#5a5a6a', '#1a1a24', '#000000') },
    pose: 'claws',
    weapon: { kind: 'dagger', tone: DARKSTEEL, glow: '#7aff6a' },
    extra: { armNear: '' },
    cape: K.cloth('#5a5a6a', '#1a1a24', '#000000'),
    motion: 'walk',
    attack: 'thrust',
  }),
  dungeon_medusa: () => humanoid({
    id: 'gmedu',
    skin: K.t('#d8f0c8', '#7aa86a', '#1e3a1a', 'skin'),
    head: { kind: 'female', hair: { tone: K.t('#c8f0a8', '#4a8a3a', '#0e2a0a', 'scale'), style: 'snakes' }, eyes: '#ffe040' },
    torso: { kind: 'plate', tone: K.BRONZE, belt: K.BRONZE },
    legs: { kind: 'snake', tone: K.t('#c8e8a8', '#4a7a3a', '#0e220a') },
    pose: 'bow',
    off: { kind: 'bow', tone: K.BRONZE },
    motion: 'float',
    attack: 'bow',
  }),
  dungeon_lizard_rider: () => quadruped({
    id: 'glizr',
    species: 'lizard',
    tone: K.t('#a8b878', '#4a5a2a', '#121a08', 'scale'),
    belly: K.t('#e8e0b0', '#c0b880', '#4a4020'),
    tail: 'lizard',
    eyes: '#ffe070',
    rider: {
      id: 'glizr',
      height: 0.9,
      skin: K.SKIN_DARKELF,
      head: { kind: 'elf', hair: { tone: K.HAIR_WHITE, style: 'long' }, helmet: { kind: 'kettle', tone: DARKSTEEL } },
      torso: { kind: 'chain', tone: DARKSTEEL, tabard: { tone: PURPLE } },
      legs: { kind: 'pants', tone: K.LEATHER_DARK },
      pose: 'spear',
      weapon: { kind: 'spear', tone: DARKSTEEL },
      motion: 'gallop',
      attack: 'thrust',
    },
    motion: 'gallop',
    attack: 'thrust',
  }),
  dungeon_minotaur: () => humanoid({
    id: 'gmino',
    height: 1.06,
    bulk: 1.4,
    skin: K.t('#c8a888', '#6a4a32', '#1e120a', 'cloth'),
    head: { kind: 'bull', horns: { tone: K.HORN, kind: 'bull' }, eyes: '#ff5a3a' },
    torso: { kind: 'bare', tone: K.t('#c8a888', '#6a4a32', '#1e120a', 'skin'), belt: K.LEATHER, skirt: 'short' },
    legs: { kind: 'hooves', tone: K.t('#a8886a', '#4a3424', '#120a06', 'cloth') },
    pose: 'twohand',
    weapon: { kind: 'greataxe', tone: DARKSTEEL },
    motion: 'walk',
    attack: 'swing',
  }),
  dungeon_deep_witch: () => humanoid({
    id: 'gwitch',
    skin: K.SKIN_DARKELF,
    head: { kind: 'female', hair: { tone: K.HAIR_WHITE, style: 'long' }, helmet: { kind: 'circlet', tone: K.t('#e8d8ff', '#a888d8', '#3a2a5a') }, eyes: SHADOW },
    torso: { kind: 'robe', tone: PURPLE, skirt: 'robe', trim: K.t('#e8d8ff', '#a888d8', '#3a2a5a'), belt: K.LEATHER_DARK },
    legs: { kind: 'pants', tone: PURPLE },
    pose: 'cast',
    off: { kind: 'orb', glow: SHADOW },
    castGlow: SHADOW,
    aura: { color: SHADOW, strength: 0.18 },
    motion: 'walk',
    attack: 'cast',
  }),
  dungeon_manticore: () => quadruped({
    id: 'gmant',
    species: 'lion',
    tone: K.t('#e8b890', '#a8603a', '#3a160a', 'skin'),
    mane: K.t('#c8806a', '#6a2a1a', '#1e0804', 'cloth'),
    wings: { tone: K.t('#c88a7a', '#6a2a2a', '#1a0606'), kind: 'bat' },
    tail: 'scorpion',
    eyes: '#ffe070',
    motion: 'fly',
    attack: 'bite',
  }),
  dungeon_hydra: () => quadruped({
    id: 'ghydra',
    species: 'lizard',
    tone: K.t('#a8d8a8', '#3a7a5a', '#0a2214', 'scale'),
    belly: K.t('#e8f0c0', '#b8c880', '#3a4a1a'),
    heads: 5,
    tail: 'lizard',
    eyes: '#ffe070',
    scale: 1.1,
    motion: 'gallop',
    attack: 'bite',
  }),
  dungeon_shadow_dragon: () => dragon({
    id: 'gsdrag',
    tone: K.t('#7a6a9a', '#221a34', '#040208', 'scale'),
    belly: K.t('#a888c8', '#4a3a6a', '#120a1e'),
    wing: K.t('#6a5a8a', '#1e1630', '#020104'),
    horn: K.t('#d8d0e0', '#7a708a', '#1e1a24', 'bone'),
    eyes: SHADOW,
    breath: SHADOW,
    aura: { color: SHADOW, strength: 0.2 },
    motion: 'fly',
    attack: 'bite',
  }),
  dungeon_shadow_matriarch: () => humanoid({
    id: 'gmatr',
    height: 1.1,
    bulk: 1.25,
    skin: K.SKIN_DARKELF,
    head: { kind: 'female', hair: { tone: K.HAIR_WHITE, style: 'long' }, helmet: { kind: 'crown', tone: K.t('#e8d8ff', '#a888d8', '#3a2a5a') }, eyes: SHADOW },
    torso: { kind: 'robe', tone: K.cloth('#8a6aa8', '#2a1a3a', '#060208'), skirt: 'robe', trim: K.GOLD, pauldrons: DARKSTEEL, belt: K.GOLD },
    legs: { kind: 'pants', tone: PURPLE },
    pose: 'cast',
    weapon: { kind: 'staff', glow: SHADOW },
    castGlow: SHADOW,
    cape: PURPLE,
    aura: { color: SHADOW, strength: 0.3 },
    motion: 'walk',
    attack: 'cast',
  }),
}
