/** Эльфы (§10.1): зелень, кора и серебро — лесные стрелки, друиды, звери и драконы */
import { type UnitSource, humanoid } from '../figures/humanoid.js'
import { quadruped } from '../figures/quadruped.js'
import { bird, dragon } from '../figures/dragon.js'
import * as K from './tones.js'

const GREEN = K.cloth('#9ad88a', '#3f8f3a', '#10280e')
const MOSS = K.cloth('#b8c88a', '#6a7a3a', '#1e2410')
const LEAF = K.t('#d8f27a', '#6aa83a', '#1a3a0a')
const SILVER = K.t('#ffffff', '#c8d0d8', '#4a5260', 'metal')
const NATURE = '#c8ff8a'

export const ELF_RIGS: Record<string, () => UnitSource> = {
  elf_sprite: () => humanoid({
    id: 'esprite',
    height: 0.66,
    headScale: 1.2,
    skin: K.t('#f0fff0', '#b8e8c0', '#3a6a4a', 'skin'),
    head: { kind: 'elf', hair: { tone: LEAF, style: 'long' }, eyes: NATURE },
    torso: { kind: 'tunic', tone: LEAF, skirt: 'short' },
    legs: { kind: 'bare' },
    pose: 'melee',
    weapon: { kind: 'dagger', tone: SILVER, glow: NATURE },
    wings: { kind: 'insect', tone: K.t('#ffffff', '#c8f8e8', '#4a8a7a'), span: 1.2 },
    aura: { color: NATURE, strength: 0.25 },
    hover: 14,
    motion: 'fly',
    attack: 'thrust',
  }),
  elf_wood_scout: () => humanoid({
    id: 'escout',
    skin: K.SKIN_ELF,
    head: { kind: 'elf', hair: { tone: K.HAIR_BLOND, style: 'short' }, helmet: { kind: 'hood', tone: MOSS } },
    torso: { kind: 'leather', tone: K.LEATHER, belt: K.LEATHER },
    legs: { kind: 'pants', tone: MOSS },
    pose: 'melee',
    weapon: { kind: 'sword', tone: SILVER, scale: 0.8 },
    off: { kind: 'none' },
    cape: MOSS,
    motion: 'walk',
    attack: 'thrust',
  }),
  elf_elven_archer: () => humanoid({
    id: 'earch',
    skin: K.SKIN_ELF,
    head: { kind: 'elf', hair: { tone: K.HAIR_BLOND, style: 'long' }, helmet: { kind: 'circlet', tone: SILVER } },
    torso: { kind: 'leather', tone: GREEN, belt: K.LEATHER, tabard: { tone: GREEN } },
    legs: { kind: 'pants', tone: K.LEATHER },
    pose: 'bow',
    off: { kind: 'bow', tone: SILVER },
    cape: GREEN,
    motion: 'walk',
    attack: 'bow',
  }),
  elf_dryad: () => humanoid({
    id: 'edryad',
    skin: K.SKIN_BARK,
    head: { kind: 'female', hair: { tone: LEAF, style: 'leaves' }, eyes: NATURE },
    torso: { kind: 'bark', tone: K.SKIN_BARK, skirt: 'long' },
    legs: { kind: 'bare' },
    pose: 'cast',
    castGlow: NATURE,
    aura: { color: NATURE, strength: 0.18 },
    motion: 'walk',
    attack: 'cast',
  }),
  elf_druid: () => humanoid({
    id: 'edruid',
    skin: K.SKIN_ELF,
    head: { kind: 'elf', beard: { tone: K.HAIR_WHITE, style: 'long' }, hair: { tone: K.HAIR_WHITE, style: 'long' }, horns: { tone: K.t('#c8a882', '#7a5a3a', '#2a1a0a', 'wood'), kind: 'long' } },
    torso: { kind: 'robe', tone: MOSS, skirt: 'robe', belt: K.LEATHER },
    legs: { kind: 'pants', tone: MOSS },
    pose: 'cast',
    weapon: { kind: 'staff', glow: NATURE },
    castGlow: NATURE,
    motion: 'walk',
    attack: 'cast',
  }),
  elf_dire_wolf: () => quadruped({
    id: 'ewolf',
    species: 'wolf',
    tone: K.t('#d8d8d0', '#7a7a74', '#1e1e1c', 'cloth'),
    mane: K.t('#f0f0e8', '#a8a8a0', '#3a3a36', 'cloth'),
    belly: K.t('#ffffff', '#c8c8c0', '#5a5a54'),
    eyes: '#ffe070',
    motion: 'gallop',
    attack: 'bite',
  }),
  elf_unicorn: () => quadruped({
    id: 'eunic',
    species: 'horse',
    tone: K.t('#ffffff', '#e4e8f0', '#6a7084', 'skin'),
    mane: K.t('#ffffff', '#d0c8ff', '#5a4a9a'),
    horn: true,
    aura: { color: '#e0d8ff', strength: 0.2 },
    motion: 'gallop',
    attack: 'thrust',
  }),
  elf_centaur: () => quadruped({
    id: 'ecent',
    species: 'horse',
    tone: K.t('#d8b890', '#8a643c', '#2a1a0a', 'skin'),
    centaur: {
      id: 'ecent',
      height: 0.9,
      skin: K.SKIN_TAN,
      head: { kind: 'elf', hair: { tone: K.HAIR_BROWN, style: 'long' } },
      torso: { kind: 'leather', tone: K.LEATHER },
      legs: { kind: 'bare' },
      pose: 'bow',
      off: { kind: 'bow', tone: K.WOOD },
      motion: 'gallop',
      attack: 'bow',
    },
    motion: 'gallop',
    attack: 'bow',
  }),
  elf_treant: () => humanoid({
    id: 'etreant',
    height: 1.12,
    bulk: 1.55,
    headScale: 0.9,
    skin: K.SKIN_BARK,
    head: { kind: 'golem', eyes: NATURE, hair: { tone: LEAF, style: 'leaves' } },
    torso: { kind: 'bark', tone: K.SKIN_BARK },
    legs: { kind: 'bare' },
    pose: 'claws',
    extra: { back: `<path d="M24,30 C18,20 22,10 30,8 C28,16 30,22 36,26 Z M70,24 C78,14 86,16 88,24 C80,22 76,26 72,32 Z" fill="#4a7a2a" stroke="#1a2a0a" stroke-width="0.6"/>` },
    motion: 'walk',
    attack: 'claw',
  }),
  elf_ranger: () => humanoid({
    id: 'erang',
    skin: K.SKIN_ELF,
    head: { kind: 'elf', hair: { tone: K.HAIR_BROWN, style: 'long' }, helmet: { kind: 'hood', tone: GREEN } },
    torso: { kind: 'leather', tone: K.LEATHER_DARK, belt: K.LEATHER, tabard: { tone: GREEN } },
    legs: { kind: 'pants', tone: K.LEATHER_DARK },
    pose: 'bow',
    off: { kind: 'bow', tone: K.WOOD },
    cape: GREEN,
    motion: 'walk',
    attack: 'bow',
  }),
  elf_phoenix: () => bird({
    id: 'ephoe',
    tone: K.t('#fff0a0', '#ff8a2a', '#7a1a04'),
    wing: K.t('#ffe070', '#ff5a1a', '#6a1004'),
    beak: K.t('#fff0c0', '#e0a828', '#6a4008'),
    crest: K.t('#ffffff', '#ffd040', '#a04a08'),
    fire: '#ff9a2a',
    eyes: '#ffffff',
    motion: 'fly',
    attack: 'bite',
  }),
  elf_forest_guardian: () => humanoid({
    id: 'eguard',
    height: 1.1,
    bulk: 1.35,
    skin: K.SKIN_ELF,
    head: { kind: 'elf', hair: { tone: K.HAIR_WHITE, style: 'long' }, helmet: { kind: 'great', tone: K.t('#d8f0b8', '#6a9a4a', '#1a2a0a', 'wood'), plume: '#6aa83a' } },
    torso: { kind: 'plate', tone: K.t('#d8f0b8', '#6a9a4a', '#1a2a0a', 'wood'), pauldrons: K.t('#d8f0b8', '#6a9a4a', '#1a2a0a', 'wood'), belt: K.LEATHER, skirt: 'short' },
    legs: { kind: 'plate', tone: K.t('#d8f0b8', '#6a9a4a', '#1a2a0a', 'wood'), boots: K.LEATHER },
    pose: 'spear',
    weapon: { kind: 'pike', tone: SILVER, glow: NATURE },
    cape: GREEN,
    motion: 'walk',
    attack: 'thrust',
  }),
  elf_silver_dragon: () => dragon({
    id: 'esdrag',
    tone: K.t('#ffffff', '#c0c8d4', '#3a4252', 'scale'),
    belly: K.t('#ffffff', '#e8eef4', '#7a8494'),
    wing: K.t('#ffffff', '#b8d0e8', '#3a5070'),
    horn: K.t('#ffffff', '#e0e8f0', '#5a6474', 'bone'),
    eyes: '#8ad8ff',
    breath: '#c8ecff',
    motion: 'fly',
    attack: 'bite',
  }),
  elf_emerald_dragon: () => dragon({
    id: 'eedrag',
    tone: K.t('#c8ffb8', '#2a9a4a', '#062a10', 'scale'),
    belly: K.t('#f0ffd8', '#b8e08a', '#3a5a1a'),
    wing: K.t('#d8ffa8', '#4ab84a', '#0a3a10'),
    horn: K.t('#fffff0', '#d8d8a8', '#5a5a3a', 'bone'),
    eyes: '#e8ff70',
    breath: '#a8ff5a',
    motion: 'fly',
    attack: 'bite',
  }),
}
