/** Крепость (§10.1): гномья сталь, бронза, руны и магма */
import { type UnitSource, humanoid } from '../figures/humanoid.js'
import { quadruped } from '../figures/quadruped.js'
import { bird, dragon } from '../figures/dragon.js'
import * as K from './tones.js'

const RUNE = '#ff8a2e'
const RUNE_BLUE = '#8ad8ff'
const CLAN = K.cloth('#e8b080', '#8a4a2a', '#2a1006')
const DWARF_SKIN = K.t('#f8d0b0', '#c88a68', '#5a3020', 'skin')
const dwarf = { height: 0.82, bulk: 1.35, headScale: 1.15 }
const BEARD_RED = K.HAIR_RED
const BEARD_BROWN = K.HAIR_BROWN
const BEARD_WHITE = K.HAIR_WHITE
const RUNES = (x: number, y: number) => `<path d="M${x},${y} l2,-3 l2,3 M${x + 6},${y} l0,-3 l2,1.5 l-2,1.5" fill="none" stroke="${RUNE}" stroke-width="0.7"/>`

export const FORTRESS_RIGS: Record<string, () => UnitSource> = {
  fortress_dwarf_defender: () => humanoid({
    id: 'fdef',
    ...dwarf,
    skin: DWARF_SKIN,
    head: { kind: 'dwarf', beard: { tone: BEARD_RED, style: 'braided' }, helmet: { kind: 'horned', tone: K.STEEL } },
    torso: { kind: 'chain', tone: K.STEEL, tabard: { tone: CLAN }, belt: K.LEATHER },
    legs: { kind: 'plate', tone: K.STEEL, boots: K.LEATHER },
    pose: 'melee',
    weapon: { kind: 'axe', tone: K.STEEL },
    off: { kind: 'shield_round', tone: K.BRONZE, emblem: RUNE },
    motion: 'walk',
    attack: 'swing',
  }),
  fortress_hammer_hurler: () => humanoid({
    id: 'fhurl',
    ...dwarf,
    skin: DWARF_SKIN,
    head: { kind: 'dwarf', beard: { tone: BEARD_BROWN, style: 'long' }, helmet: { kind: 'cap', tone: K.BRONZE } },
    torso: { kind: 'leather', tone: K.LEATHER, belt: K.LEATHER },
    legs: { kind: 'pants', tone: CLAN, boots: K.LEATHER },
    pose: 'throw',
    weapon: { kind: 'hammer', tone: K.STEEL, glow: RUNE },
    motion: 'walk',
    attack: 'bow',
  }),
  fortress_boar_rider: () => quadruped({
    id: 'fboar',
    species: 'boar',
    tone: K.t('#a88a6a', '#5a4030', '#1a100a', 'cloth'),
    mane: K.FUR_DARK,
    tusks: true,
    tail: 'stub',
    eyes: '#ffb040',
    rider: {
      id: 'fboar',
      ...dwarf,
      height: 0.74,
      skin: DWARF_SKIN,
      head: { kind: 'dwarf', beard: { tone: BEARD_RED, style: 'braided' }, helmet: { kind: 'kettle', tone: K.STEEL } },
      torso: { kind: 'chain', tone: K.STEEL, tabard: { tone: CLAN } },
      legs: { kind: 'pants', tone: CLAN },
      pose: 'melee',
      weapon: { kind: 'axe', tone: K.STEEL },
      motion: 'gallop',
      attack: 'swing',
    },
    motion: 'gallop',
    attack: 'swing',
  }),
  fortress_shieldbearer: () => humanoid({
    id: 'fshield',
    ...dwarf,
    skin: DWARF_SKIN,
    head: { kind: 'dwarf', beard: { tone: BEARD_BROWN, style: 'braided' }, helmet: { kind: 'great', tone: K.STEEL } },
    torso: { kind: 'plate', tone: K.STEEL, pauldrons: K.BRONZE, belt: K.LEATHER },
    legs: { kind: 'plate', tone: K.STEEL, boots: K.STEEL },
    arms: { sleeve: K.STEEL, gauntlet: K.STEEL },
    pose: 'melee',
    weapon: { kind: 'hammer', tone: K.STEEL },
    off: { kind: 'shield_tower', tone: K.BRONZE, emblem: RUNE },
    motion: 'walk',
    attack: 'swing',
  }),
  fortress_rune_caster: () => humanoid({
    id: 'frune',
    ...dwarf,
    skin: DWARF_SKIN,
    head: { kind: 'dwarf', beard: { tone: BEARD_WHITE, style: 'long' }, hair: { tone: BEARD_WHITE, style: 'long' }, eyes: RUNE },
    torso: { kind: 'robe', tone: CLAN, skirt: 'long', belt: K.BRONZE, trim: K.BRONZE },
    legs: { kind: 'pants', tone: CLAN, boots: K.LEATHER },
    pose: 'cast',
    weapon: { kind: 'staff', glow: RUNE },
    castGlow: RUNE,
    extra: { torso: RUNES(46, 50) },
    motion: 'walk',
    attack: 'cast',
  }),
  fortress_clan_elder: () => humanoid({
    id: 'felder',
    ...dwarf,
    skin: DWARF_SKIN,
    head: { kind: 'dwarf', beard: { tone: BEARD_WHITE, style: 'braided' }, helmet: { kind: 'crown', tone: K.GOLD } },
    torso: { kind: 'plate', tone: K.BRONZE, tabard: { tone: CLAN, emblem: '#f2c14e' }, pauldrons: K.GOLD, belt: K.GOLD },
    legs: { kind: 'plate', tone: K.BRONZE, boots: K.BRONZE },
    arms: { sleeve: K.BRONZE, gauntlet: K.BRONZE },
    pose: 'twohand',
    weapon: { kind: 'warhammer', tone: K.STEEL, glow: RUNE },
    cape: CLAN,
    motion: 'walk',
    attack: 'swing',
  }),
  fortress_ironguard: () => humanoid({
    id: 'firon',
    ...dwarf,
    bulk: 1.45,
    skin: DWARF_SKIN,
    head: { kind: 'dwarf', beard: { tone: BEARD_BROWN, style: 'braided' }, helmet: { kind: 'great', tone: K.IRON, plume: '#8a4a2a' } },
    torso: { kind: 'plate', tone: K.IRON, pauldrons: K.IRON, belt: K.LEATHER, skirt: 'short' },
    legs: { kind: 'plate', tone: K.IRON, boots: K.IRON },
    arms: { sleeve: K.IRON, gauntlet: K.IRON },
    pose: 'twohand',
    weapon: { kind: 'greataxe', tone: K.STEEL },
    motion: 'walk',
    attack: 'swing',
  }),
  fortress_ballista_crew: () => humanoid({
    id: 'fball',
    ...dwarf,
    skin: DWARF_SKIN,
    head: { kind: 'dwarf', beard: { tone: BEARD_RED, style: 'long' }, helmet: { kind: 'kettle', tone: K.BRONZE } },
    torso: { kind: 'leather', tone: K.LEATHER, belt: K.LEATHER, tabard: { tone: CLAN } },
    legs: { kind: 'pants', tone: CLAN, boots: K.LEATHER },
    pose: 'crossbow',
    off: { kind: 'crossbow', tone: K.WOOD },
    motion: 'walk',
    attack: 'bow',
  }),
  fortress_roc: () => bird({
    id: 'froc',
    tone: K.t('#d8b890', '#7a5a3a', '#22160a'),
    wing: K.t('#c8a882', '#5a3c22', '#1a0e06'),
    beak: K.t('#fff0c0', '#d8b048', '#5a3a08'),
    crest: K.t('#ffffff', '#e8e0d0', '#7a7060'),
    scale: 1.05,
    motion: 'fly',
    attack: 'bite',
  }),
  fortress_mountain_bear: () => quadruped({
    id: 'fbear',
    species: 'bear',
    tone: K.t('#b89a7a', '#5e4430', '#1a100a', 'cloth'),
    barding: { tone: K.BRONZE, trim: RUNE },
    tail: 'stub',
    eyes: '#ffb040',
    motion: 'gallop',
    attack: 'claw',
  }),
  fortress_magma_golem: () => humanoid({
    id: 'fmagma',
    height: 1.1,
    bulk: 1.55,
    headScale: 0.82,
    skin: K.SKIN_MAGMA,
    head: { kind: 'golem', eyes: '#ffd070' },
    torso: { kind: 'stone', tone: K.SKIN_MAGMA, pauldrons: K.SKIN_MAGMA },
    legs: { kind: 'bare' },
    pose: 'melee',
    weapon: { kind: 'none' },
    aura: { color: '#ff8a2a', strength: 0.3 },
    extra: { torso: `<path d="M40,42 l6,4 l-2,6 l6,4 M56,34 l-3,6 l5,5 M44,60 l8,2" fill="none" stroke="#ffd070" stroke-width="1.2"/>` },
    motion: 'walk',
    attack: 'swing',
  }),
  fortress_rune_golem: () => humanoid({
    id: 'frgol',
    height: 1.1,
    bulk: 1.55,
    headScale: 0.82,
    skin: K.SKIN_STONE,
    head: { kind: 'golem', eyes: RUNE_BLUE },
    torso: { kind: 'stone', tone: K.SKIN_STONE, pauldrons: K.SKIN_STONE },
    legs: { kind: 'bare' },
    pose: 'melee',
    weapon: { kind: 'none' },
    aura: { color: RUNE_BLUE, strength: 0.18 },
    extra: { torso: `<path d="M44,40 l2,-4 l2,4 M50,46 l0,-4 l3,2 l-3,2 M42,54 l4,0 l-2,3 Z" fill="none" stroke="${RUNE_BLUE}" stroke-width="0.9"/>` },
    motion: 'walk',
    attack: 'swing',
  }),
  fortress_magma_dragon: () => dragon({
    id: 'fmdrag',
    tone: K.t('#ffb070', '#8a2a14', '#1e0602', 'scale'),
    belly: K.t('#fff0a0', '#ffa840', '#7a2a08'),
    wing: K.t('#ff9a5a', '#7a2a14', '#1a0602'),
    horn: K.t('#5a5050', '#2a2222', '#080606', 'bone'),
    eyes: '#ffe070',
    breath: '#ff7a1a',
    aura: { color: '#ff7a1a', strength: 0.22 },
    grounded: true,
    motion: 'walk',
    attack: 'bite',
  }),
  fortress_steam_juggernaut: () => humanoid({
    id: 'fjugg',
    height: 1.1,
    bulk: 1.6,
    headScale: 0.78,
    skin: K.BRASS,
    head: { kind: 'golem', eyes: RUNE, helmet: { kind: 'great', tone: K.BRASS } },
    torso: { kind: 'metal', tone: K.BRASS, pauldrons: K.IRON, belt: K.IRON },
    legs: { kind: 'plate', tone: K.IRON, boots: K.IRON },
    arms: { sleeve: K.IRON, gauntlet: K.BRASS },
    pose: 'crossbow',
    off: { kind: 'crossbow', tone: K.IRON },
    extra: {
      back: `<path d="M30,26 l0,-12 l6,0 l0,12 Z" fill="#3a3028" stroke="#120c08" stroke-width="0.6"/><circle cx="33" cy="10" r="5" fill="#d8d0c8" opacity="0.45"/><circle cx="29" cy="4" r="4" fill="#e8e0d8" opacity="0.3"/>`,
    },
    motion: 'walk',
    attack: 'bow',
  }),
}
