/** Маги (§10.1): лазурь, латунь и камень — конструкты, чародеи и стихии */
import { C } from '../kit.js'
import { type UnitSource, humanoid } from '../figures/humanoid.js'
import { quadruped } from '../figures/quadruped.js'
import { dragon } from '../figures/dragon.js'
import * as K from './tones.js'

const AZURE = K.cloth('#8ad0ec', '#2a8fb0', '#0a2a3a')
const VIOLET = K.cloth('#c8b8ff', '#6a58c0', '#1a1240')
const ARCANE = '#8ad8ff'

export const WIZARD_RIGS: Record<string, () => UnitSource> = {
  wizard_gremlin: () => humanoid({
    id: 'wgrem',
    height: 0.74,
    bulk: 1.05,
    headScale: 1.25,
    skin: K.t('#c8d8e0', '#7a96a8', '#24323c', 'skin'),
    head: { kind: 'goblin', ears: 'big', eyes: '#ffe070' },
    torso: { kind: 'leather', tone: K.LEATHER, belt: K.BRASS },
    legs: { kind: 'bare' },
    pose: 'cast',
    castGlow: '#ffe070',
    off: { kind: 'none' },
    motion: 'walk',
    attack: 'cast',
  }),
  wizard_brass_sentry: () => humanoid({
    id: 'wsent',
    height: 0.98,
    bulk: 1.2,
    skin: K.BRASS,
    head: { kind: 'golem', eyes: ARCANE },
    torso: { kind: 'metal', tone: K.BRASS, belt: K.IRON },
    legs: { kind: 'plate', tone: K.BRASS, boots: K.BRASS },
    arms: { sleeve: K.BRASS, gauntlet: K.BRASS },
    pose: 'spear',
    weapon: { kind: 'spear', tone: K.BRASS },
    off: { kind: 'shield_round', tone: K.BRASS, emblem: '#2a8fb0' },
    motion: 'walk',
    attack: 'thrust',
  }),
  wizard_gargoyle: () => humanoid({
    id: 'wgarg',
    height: 0.94,
    bulk: 1.15,
    skin: K.SKIN_STONE,
    head: { kind: 'demon', horns: { tone: K.SKIN_STONE, kind: 'small' }, eyes: ARCANE },
    torso: { kind: 'stone', tone: K.SKIN_STONE },
    legs: { kind: 'bare' },
    pose: 'claws',
    wings: { kind: 'bat', tone: K.SKIN_STONE, span: 0.9 },
    tail: { kind: 'demon', tone: K.SKIN_STONE },
    hover: 6,
    motion: 'fly',
    attack: 'claw',
  }),
  wizard_stone_hound: () => quadruped({
    id: 'whound',
    species: 'wolf',
    tone: K.SKIN_STONE,
    mane: K.t('#a8a49a', '#6a665c', '#1e1c18'),
    eyes: ARCANE,
    tail: 'stub',
    motion: 'gallop',
    attack: 'bite',
  }),
  wizard_iron_golem: () => humanoid({
    id: 'wiron',
    height: 1.06,
    bulk: 1.45,
    headScale: 0.85,
    skin: K.IRON,
    head: { kind: 'golem', eyes: '#ff9a3a' },
    torso: { kind: 'metal', tone: K.IRON, pauldrons: K.IRON },
    legs: { kind: 'plate', tone: K.IRON, boots: K.IRON },
    arms: { sleeve: K.IRON, gauntlet: K.IRON },
    pose: 'melee',
    weapon: { kind: 'none' },
    motion: 'walk',
    attack: 'swing',
  }),
  wizard_clay_golem: () => humanoid({
    id: 'wclay',
    height: 1.04,
    bulk: 1.4,
    headScale: 0.85,
    skin: K.SKIN_CLAY,
    head: { kind: 'golem', eyes: '#ffe070' },
    torso: { kind: 'stone', tone: K.SKIN_CLAY },
    legs: { kind: 'bare' },
    pose: 'melee',
    weapon: { kind: 'none' },
    extra: { torso: `<path d="M44,40 l4,2 l-1,4 M52,52 l3,1" fill="none" stroke="#ffe070" stroke-width="0.8" opacity="0.8"/>` },
    motion: 'walk',
    attack: 'swing',
  }),
  wizard_mage: () => humanoid({
    id: 'wmage',
    skin: K.SKIN_HUMAN,
    head: { kind: 'human', beard: { tone: K.HAIR_GREY, style: 'long' }, helmet: { kind: 'hood', tone: AZURE } },
    torso: { kind: 'robe', tone: AZURE, skirt: 'robe', trim: K.GOLD, belt: K.GOLD },
    legs: { kind: 'pants', tone: AZURE },
    pose: 'cast',
    weapon: { kind: 'staff', glow: ARCANE },
    castGlow: ARCANE,
    motion: 'walk',
    attack: 'cast',
  }),
  wizard_enchanter: () => humanoid({
    id: 'wench',
    skin: K.SKIN_PALE,
    head: { kind: 'female', hair: { tone: K.HAIR_BLACK, style: 'long' }, helmet: { kind: 'circlet', tone: K.GOLD } },
    torso: { kind: 'robe', tone: VIOLET, skirt: 'robe', trim: K.GOLD, belt: K.GOLD },
    legs: { kind: 'pants', tone: VIOLET },
    pose: 'cast',
    off: { kind: 'book', tone: VIOLET, emblem: C.gold, glow: '#d8b8ff' },
    castGlow: '#d8b8ff',
    aura: { color: '#b89aff', strength: 0.15 },
    motion: 'walk',
    attack: 'cast',
  }),
  wizard_genie: () => humanoid({
    id: 'wgenie',
    bulk: 1.15,
    skin: K.SKIN_GENIE,
    head: { kind: 'human', beard: { tone: K.HAIR_BLACK, style: 'short' }, helmet: { kind: 'turban', tone: K.cloth('#fff8e0', '#e8d8a0', '#7a6a3a') }, eyes: '#ffffff' },
    torso: { kind: 'bare', tone: K.SKIN_GENIE, belt: K.GOLD },
    legs: { kind: 'smoke', tone: K.t('#d8f0ff', '#5a9ae0', '#1a3a6a') },
    arms: { sleeve: K.SKIN_GENIE },
    pose: 'melee',
    weapon: { kind: 'scimitar', tone: K.STEEL },
    aura: { color: ARCANE, strength: 0.18 },
    hover: 4,
    motion: 'float',
    attack: 'swing',
  }),
  wizard_naga: () => humanoid({
    id: 'wnaga',
    skin: K.t('#d0f0e0', '#6aaa8a', '#1a3a2a', 'skin'),
    head: { kind: 'female', hair: { tone: K.HAIR_BLACK, style: 'long' }, helmet: { kind: 'crown', tone: K.GOLD } },
    torso: { kind: 'plate', tone: K.GOLD, belt: K.GOLD },
    legs: { kind: 'snake', tone: K.t('#a8e0b8', '#3a8a5a', '#0a2a14') },
    arms: { sleeve: K.t('#d0f0e0', '#6aaa8a', '#1a3a2a', 'skin') },
    pose: 'melee',
    weapon: { kind: 'scimitar', tone: K.GOLD },
    off: { kind: 'buckler', tone: K.GOLD, emblem: '#2a8fb0' },
    motion: 'float',
    attack: 'swing',
  }),
  wizard_stone_colossus: () => humanoid({
    id: 'wcolos',
    height: 1.12,
    bulk: 1.6,
    headScale: 0.8,
    skin: K.SKIN_STONE,
    head: { kind: 'golem', eyes: ARCANE },
    torso: { kind: 'stone', tone: K.SKIN_STONE, pauldrons: K.SKIN_STONE },
    legs: { kind: 'bare' },
    pose: 'melee',
    weapon: { kind: 'none' },
    extra: { torso: `<path d="M40,36 l6,4 l2,8 M56,30 l-2,6" fill="none" stroke="${ARCANE}" stroke-width="0.9" opacity="0.85"/>` },
    motion: 'walk',
    attack: 'swing',
  }),
  wizard_storm_elemental: () => humanoid({
    id: 'wstorm',
    bulk: 1.15,
    skin: K.t('#e0f0ff', '#6a8ab0', '#1a2a40', 'skin'),
    head: { kind: 'golem', eyes: '#ffffff', hair: { tone: K.t('#ffffff', '#a8c8f0', '#3a5a8a'), style: 'wild' } },
    torso: { kind: 'bare', tone: K.t('#e0f0ff', '#6a8ab0', '#1a2a40', 'skin') },
    legs: { kind: 'smoke', tone: K.t('#e8f4ff', '#7a9ac8', '#2a3a5a') },
    pose: 'claws',
    aura: { color: '#9ad8ff', strength: 0.3 },
    extra: { front: `<path d="M30,30 l5,6 l-3,1 l5,7 M72,24 l-4,6 l3,0 l-4,8" fill="none" stroke="#e8f8ff" stroke-width="1" stroke-linejoin="round"/>` },
    hover: 4,
    motion: 'float',
    attack: 'claw',
  }),
  wizard_titan: () => humanoid({
    id: 'wtitan',
    height: 1.12,
    bulk: 1.35,
    skin: K.SKIN_TAN,
    head: { kind: 'human', beard: { tone: K.HAIR_WHITE, style: 'long' }, hair: { tone: K.HAIR_WHITE, style: 'long' }, helmet: { kind: 'circlet', tone: K.GOLD } },
    torso: { kind: 'plate', tone: K.GOLD, skirt: 'long', tabard: { tone: AZURE }, pauldrons: K.GOLD, belt: K.LEATHER },
    legs: { kind: 'plate', tone: K.GOLD, boots: K.GOLD },
    pose: 'cast',
    castGlow: '#c8ecff',
    aura: { color: '#c8ecff', strength: 0.2 },
    extra: { armNear: `<path d="M74,28 l6,-6 l-1,4 l6,-6" fill="none" stroke="#ffffff" stroke-width="1"/>` },
    motion: 'walk',
    attack: 'cast',
  }),
  wizard_arcane_dragon: () => dragon({
    id: 'wdrag',
    tone: K.t('#c8b8ff', '#5a4ab0', '#120c3a', 'scale'),
    belly: K.t('#e8f4ff', '#9ad0f0', '#2a5a8a'),
    wing: K.t('#a8f0ff', '#4a8ad8', '#0c2050'),
    horn: K.t('#ffffff', '#b8e8ff', '#3a6a8a', 'bone'),
    eyes: '#ffffff',
    breath: ARCANE,
    aura: { color: ARCANE, strength: 0.2 },
    motion: 'fly',
    attack: 'bite',
  }),
}
