export * from './types.js'
export * from './constants.js'
export * from './rng.js'
export * from './grid.js'
export { UNITS, TIER_BASELINE, calibratedPower, getUnit, findUnit, unitsOfRace, baseUnitOf } from './data/units.js'
export { POWER_CALIBRATION, RACE_POWER_CALIBRATION } from './data/calibration.js'
export { unitPower, weightFromPower } from './data/power.js'
export { SPELLS, getSpell, getAvailableSpells, type SpellTemplate, type SpellTargeting } from './data/spells.js'
export * from './hero.js'
export * from './army.js'
export * from './deploy.js'
export * from './rating.js'
export { createBattle, applyAction, applyTimeout, activeActor, casterPower, type Participant, type CreateBattleInput, type ActionResult } from './battle/engine.js'
export { IllegalActionError, effectiveInitiative, effectiveSpeed, shootMoveLimit, totalHp } from './battle/helpers.js'
export { computeDamage, attackMultiplier, roleMultiplier } from './battle/combat.js'
export { isValidSpellTarget, lightningBoltDamage } from './battle/magic.js'
export { forecastAction, killsFrom, type DamageForecast } from './battle/forecast.js'
export { movePositions, attackPositions, type Position } from './battle/movement.js'
export { candidateActions } from './ai/candidates.js'
export { chooseBotAction, material, type BotDifficulty } from './ai/bot.js'
export { createBotHero, createBotArmy } from './ai/army.js'
export { simulateBattle, type SimResult } from './ai/simulate.js'
